### ISSUE TITLE
Crash with Pehkui 3.0+

### ISSUE THREAD

**Issue by ghost** [GiantLuigi4/Smaller-Units#163]
Startup crash with Pehkui 3.0+ enabled:

Main error seems to be: **Exception message: java.lang.NoSuchFieldError: BASE**

Full crash report:
```
-- Head --
Thread: Render thread
Stacktrace:
	at tfc.smallerunits.Smallerunits.<init>(Smallerunits.java:81) ~[?:1.16] {re:classloading}
-- MOD smallerunits --
Details:
	Mod File: smallerunits-1.16.jar
	Failure message: Smallerunits (smallerunits) has failed to load correctly
		java.lang.NoSuchFieldError: BASE
	Mod Version: 1.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: BASE
Stacktrace:
	at tfc.smallerunits.Smallerunits.<init>(Smallerunits.java:81) ~[?:1.16] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3126/1597736125.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3226/725579524.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
```

**Comment by GiantLuigi4** [comment]
*a*
*opens intelliJ 2019, which in turn opens intelliJ 2020*

**Comment by ghost** [comment]
???

**Comment by GiantLuigi4** [comment]
I use an older version of intelliJ for working on SU, and I tend to drop whatever I'm doing if I notice a new issue on the github
for some reason, my copy of intelliJ 2020 is listed as intelliJ 2019 on my pc
I'll (hopefully) have a new jar soon

(also, fun thing, I still kinda need to support older pehkui while also supporting newer pehkui)

**Comment by ghost** [comment]
why do u need to support older pehkui versions? they all are the same for each minecraft version

**Comment by GiantLuigi4** [comment]
newer Pehkui versions crash with Vivecraft, and I want to setup a VR server with SU and Pehkui

**Comment by ghost** [comment]
ahh, i see

**Comment by GiantLuigi4** [comment]
should be fixed, I just gotta test it now

edit: now it's "java.lang.RuntimeException: BASE"

update: dev envro just crashes upon loading a world, gonna try in production

**Comment by GiantLuigi4** [comment]
```java
[21:27:51] [Render thread/DEBUG] [mixin/]: Mixing compat116.ProjectileUtilMixin from pehkui.mixins.json into net.minecraft.entity.projectile.ProjectileHelper
[21:27:51] [Render thread/DEBUG] [mixin/]: Mixing compat116plus.ProjectileUtilMixin from pehkui.mixins.json into net.minecraft.entity.projectile.ProjectileHelper
[21:27:51] [Render thread/DEBUG] [mixin/]: Mixing rendering.unit_in_block.ChunkRenderCacheAccessor from smaller_units.mixins.json into net.minecraft.client.renderer.chunk.ChunkRenderCache
[21:27:51] [Render thread/DEBUG] [mixin/]: Mixing client.compat115plus.InGameOverlayRendererMixin from pehkui.mixins.json into net.minecraft.client.renderer.OverlayRenderer
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code -1
```
Weird, it just crashes with no visible exception in both dev env and  production
I assumed it was just a mod conflict in dev, but it's not

I'll have to look into this tomorrow

I'm personally using [pehkui 2.30](https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3419504), but SU probably works with up to [2.5.3](https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3501593), if you wanna just use that until I fix this

**Comment by ghost** [comment]
i see, thanks for the help!

**Comment by GiantLuigi4** [comment]
[SU with Pehk 3.0 support](https://cdn.discordapp.com/attachments/892136637604171806/917600299349344316/smallerunits-1.16.jar)

Turns out, SU worked with pehkui 3.0, however one of the other mods I use in dev envro didn't
Said other mod is another mod I'm working on, which I'm making pretty much exclusively for sake of SU

**Comment by EightBlade** [comment]
Did as was instructed and a similar error happened. Posting it here for brevity. https://pastebin.com/Yw15qLtB

**Comment by GiantLuigi4** [comment]
@EightBlade
Can I suggest removing three core, shrink (if you have it), and gullivern?
Smaller Units has optional deps on all of those, due to the fact that all three of them do the same thing, just in different ways

As for that issue, I have never seen it before, however, I am noticing `Objects.requireNonNull`, which I don’t have anymore, if I ever had it?
However, it looks like pehkui is failing to initialize correctly, causing smaller units to then crash the game

I’mma assume you basically just updated pehkui?
If so, try going back to pehkui 2.x, 2.5.3 is linked above
