### ISSUE TITLE
Entity in world, wait entity wasn't removed

### ISSUE THREAD

**Issue by GiantLuigi4** [GiantLuigi4/Smaller-Units#165]
Entities which came from a small world seem to continue to think that they're from the small world

```java
Caused by: java.lang.NullPointerException
	at tfc.smallerunits.utils.ExternalUnitInteractionContext.<init>(ExternalUnitInteractionContext.java:39) ~[?:?] {re:classloading}
	at tfc.smallerunits.utils.world.server.FakeServerWorld.getBlockState(FakeServerWorld.java:281) ~[?:?] {re:classloading}
	at net.minecraft.pathfinding.GroundPathNavigator.getPathToPos(SourceFile:44) ~[forge:?] {re:classloading}
	at net.minecraft.pathfinding.GroundPathNavigator.getPathToEntity(SourceFile:73) ~[forge:?] {re:classloading}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.shouldExecute(MeleeAttackGoal.java:54) ~[forge:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.shouldExecute(SourceFile:22) ~[forge:?] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_292] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_292] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_292] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_292] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_292] {}
```

**Comment by GiantLuigi4** [comment]
fixed by [6f5324b](https://github.com/GiantLuigi4/Smaller-Units/commit/6f5324b403e321613b0b6359a257f6e36fbd542a)
